springdoc:
  show-actuator: false
  default-produces-media-type: application/json
  swagger-ui:
    path: /doc/api
    disable-swagger-default-url: true
    operations-sorter: alpha

logging:
  level:
    br:
      com:
        teknologi: DEBUG

aws:
  dynamodb:
    tablePrefix:
    region: us-east-1
    endpoint: http://localhost:4566
    accesskey: local
    secretkey: local
